name: Issue Notifier
on:
  issues:
    types: [opened, closed, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const repo = context.repo;
            const action = context.payload.action;
            
            // Create Discord message
            const message = {
              content: `📋 Issue ${action} in ${repo.owner}/${repo.repo}`,
              embeds: [{
                title: `#${issue.number}: ${issue.title}`,
                description: issue.body || 'No description',
                url: issue.html_url,
                color: issue.state === 'open' ? 0x00ff00 : 0xff0000,
                fields: [
                  {
                    name: 'Author',
                    value: issue.user.login,
                    inline: true
                  },
                  {
                    name: 'State',
                    value: issue.state,
                    inline: true
                  },
                  {
                    name: 'Labels',
                    value: issue.labels.map(l => l.name).join(', ') || 'None',
                    inline: true
                  }
                ],
                footer: {
                  text: `GitHub Issue • ${action}`
                },
                timestamp: new Date().toISOString()
              }]
            };
            
            // Send to Discord
            await fetch(process.env.DISCORD_WEBHOOK, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(message)
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
